### ISSUE TITLE
Unable to  process braw file

### ISSUE THREAD

**Issue by DeriZSY** [anibali/pybraw#3]
I collect a video with BMD camera, and try to process the video with the extract frame in the example. Get the following error:
```python
  File "examples/extract_frame.py", line 67, in <module>
    main(sys.argv[1:])
  File "examples/extract_frame.py", line 38, in main
    clip = verify(codec.OpenClip(opts.input))
  File "/home/zhangsiyu/miniconda3/envs/pybraw/lib/python3.7/site-packages/pybraw/__init__.py", line 32, in verify
    assert result.is_success(), f'unsuccessful result code: {ResultCode(result).to_hex()} ({ResultCode(result).name})'
AssertionError: unsuccessful result code: 0x80000008 (E_FAIL)
```
I tried the same code with that sample braw file provided `Filmplusgear-skiers-Samnaun-2019-dci-Q5.braw` and everything is fine.

`pytest tests` says
```python
FAILED tests/test_torch.py::test_read_frames[device_cuda0] - ValueError: Pipeline blackmagicRawPipelineCUDA is not supported by this machine
FAILED tests/test_torch.py::test_read_frames[device_cuda1] - ValueError: Pipeline blackmagicRawPipelineCUDA is not supported by this machine

```
with the provided sample input

**Comment by DeriZSY** [comment]
I also tried to install this repo with the latest Blackmagic RAW SDK instead of the suggsted one. The results are even worse, most of tests during pytest step failed even with the provided sample braw file.
Below is some properties of my video, compared with the sample braw file. Hope this would help
<img width="796" alt="Screenshot 2024-11-11 at 14 41 13" src="https://github.com/user-attachments/assets/bc0463b0-3efc-4cc2-a9f4-391229eeab38">

**Comment by anibali** [comment]
Unfortunately I do not own any Blackmagic equipment and do not have the time to investigate compatibility issues. I will now archive the repository to indicate that it is no longer maintained.
